version: '3.7'

services:
  database:
   image: postgres:9.6
   container_name: shared_db # remmar 20190912 klockan 16:12
   env_file:
     - ./env/.env.postgres
   ports:
      - 5432:5432
   volumes:
     - ./customization/1-init-schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
     - db_data_psql:/var/lib/postgresql/data     
    
  seqdb:
   image: ${IMAGE}
   container_name: seqdb
   ports:
       - "8080:8080" 
   environment:
      VIRTUAL_HOST: seqdb-beta.dina-web.net
      spring.datasource.url: jdbc:postgresql://database/seqdb_prod?currentSchema=seqdb
      spring.datasource.username: seqdb_webapp
      spring.datasource.password: changeme
      spring.liquibase.user: seqdb_migration
      spring.liquibase.password: changeme2
      spring.liquibase.contexts: schema-change, initial-data, data-migration, initial-cnc-data
      import-sample-accounts: "true"
   #links:
   #  - database:database

volumes:
  db_data_psql:

networks:
  default:
    external:
       name: proxy-docker_default
