version: '3.3'

services:
  db:
   image: postgres:9.6
   #container_name: shared_seqdb_database
   container_name: db
   env_file:
     #- ./env/.postgres
     - ./env/.env.postgres
   ports:
      - 5432:5432
   volumes:
     - ./postgres-docker/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    
  seqdb:
   image: ${IMAGE}
   container_name: seqdb
   environment:
     - VIRTUAL_HOST=seqdb.nrm.se
     - VIRTUAL_PORT=8080
   links:
     - db:db

  adminer:
    image: adminer
    container_name: admin-postgres
    ports:
      - 18080:8080

  seqpublic:
   image: dina/seqdb_ui:3.32b-SNAPSHOT
   container_name: seqdb_public
   environment:
    - VIRTUAL_HOST=seqpublic.nrm.se
   #external_links: 
   # - db:db
   #extra_hosts:
   # - "db:0.0.0.0"

#volumes:
#  db_data_imageservice:

networks:
  default:
    external:
       name: proxy-docker_default
