version: '3.3'

services:
  db:
   image: mysql:5.6
   container_name: shared_seqdb_database
   env_file: 
     - ./env/.env.mysql
   ports:
    - 3306:3306
   volumes:
     - ./mysql_datadir:/var/lib/mysql
     - ./mysql_autoload:/docker-entrypoint-initdb.d:ro
     - ./mysql_conf.d:/etc/mysql/conf.d
  
  seqdb:
   image: dina/seqdb:v3.28.1b
   container_name: seqdb
   environment:
     - VIRTUAL_HOST=seqdb.nrm.se
     - VIRTUAL_PORT=8080
   links:
     - db:db

networks:
  default:
    external:
       name: proxy-docker_default
