version: '3.3'

services:

  db:
   image: mysql:5.6
   container_name: shared_seqdb_database
   env_file: 
     - ./env/.env.mysql
   ports:
    - 3306:3306
   volumes:
     - ./mysql_datadir:/var/lib/mysql
     - ./mysql_autoload:/docker-entrypoint-initdb.d:ro
     - ./mysql_conf.d:/etc/mysql/conf.d
  
  tomcat:
   image: dina/seqdb:v3.18.1
   container_name: seqdb
   env_file: .env 
   #ports:
   #  - "8080:8080"
   environment:
     - VIRTUAL_HOST=seqdb.nrm.se
     - VIRTUAL_PORT=8080
   links:
     - db:db
   volumes:
     - ./srv/logs:/opt/tomcat/logs

networks:
  default:
    external:
       name: proxy-docker_default
