fs.tomcat:
  image: tianon/true
  volumes:
    - ./srv/releases:/opt/tomcat/releases
    - ./srv/logs:/opt/tomcat/logs
    - ./srv/deployments:/opt/tomcat/webapps

fs.db:
  image: tianon/true
  volumes:
    - ./mysql_datadir:/var/lib/mysql:z
    - ./mysql_shr:/shr:z
    - ./mysql_autoload:/docker-entrypoint-initdb.d:ro
    - ./mysql_conf.d:/etc/mysql/conf.d:z
db:
  image: mysql:5.6
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_ROOT_PASSWORD=supersecret
    - MYSQL_DATABASE=seqdbweb
    - MYSQL_USER=naturalist
    - MYSQL_PASSWORD=passw0rd12
  volumes_from:
    - fs.db

tomcat:
  build: tomcat
  environment:
    - VIRTUAL_HOST=seqdb.local
  labels:
    - "letsencrypt.nocert=true"
  ports:
    - "8080:8080"
  links:
   - db:db
  volumes_from:
  - fs.tomcat

proxy:
#  image: eforce21/letsencrypt-nginx-proxy
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
