version: '3.7'

services: 
  adminer:
    image: adminer:4.7.3-standalone
    container_name: admin-postgres
    environment:
    - VIRTUAL_HOST=seqdb-admin.nrm.se
    ports:
      - 18080:8080

networks:
  default:
    external:
       name: proxy-docker_default
