version: '3.3'

services:
  db:
   image: postgres:9.6
   container_name: shared_seqdb_database
   env_file:
     - ./env/.postgres
   ports:
      - 5432:5432
   volumes:
    - db_data_imageservice:/var/lib/postgresql/data

  seqdb:
   image: ${IMAGE}
   container_name: seqdb
   environment:
     - VIRTUAL_HOST=seqdb.nrm.se
     - VIRTUAL_PORT=8080
   links:
     - db:db

  adminer:
    image: adminer
    container_name: administer-db
    ports:
      - 18080:8080

volumes:
  db_data_imageservice:

networks:
  default:
    external:
       name: proxy-docker_default
